version: "3.8"

services:
  api:
    build:
      context: .
      target: prod
    restart: always
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8000
      - MONGODB_URI=${MONGODB_URI}
