version: "3.8"

services:
  api:
    build:
      context: .
      target: build
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:6.0.5
    expose:
      - "27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
