version: "3.8"

services:
  api:
    build:
      context: .
      target: build
    ports:
      - 8000:8000
      - 9229:9229
    environment:
      - SERVER_PORT=8000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
