version: "3.8"

services:
  api:
    build:
      context: .
      target: build
    ports:
      - ${SERVER_PORT:-8000}:${SERVER_PORT:-8000}
      - 9229:9229
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    tty: true
    command: npm run dev

  mongo:
    image: mongo:6.0.5
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
