version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  api:
    build:
      context: .
      target: prod
    restart: always
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8000
      - MONGODB_URI=${MONGODB_URI}
