version: "3.8"

services:
  api:
    build:
      context: .
      target: prod
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - SERVER_PORT=3000
      - MONGODB_URI=${MONGODB_URI}
