version: "3.8"

services:
  api:
    image: ghcr.io/casantosmu/spain-weather:main
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8000
      - MONGODB_URI=${MONGODB_URI}
