name: CI

on:
  pull_request:
    branches: [main]

jobs:
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        script: ["check:format", "check:lint", "check:docs", "check:types"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Check Code ${{ matrix.script }}
        run: npm run ${{ matrix.script }}

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build the mongo image
        run: docker compose up --build -d mongo

      - name: Copy example test environment file to .env.test
        run: cp .env.test.example .env.test

      - name: Run tests
        run: docker compose run --rm api npm run test -- --coverage
